### ISSUE TITLE
Adição de novas funcionalidades ao sistema

### ISSUE THREAD

**Issue by HectorSemenssato** [camilla-sr/auto-agenda#10]
Funcionalidade 1: válvula de escape "0. Voltar" na edição de "Funcionário" e "Peça" (principal)

![image](https://github.com/user-attachments/assets/01542d85-cd85-4bd1-8bd7-1e85a3190143)

![image](https://github.com/user-attachments/assets/a4c34824-ac75-452b-b68c-7439103e88ee)

Funcionalidade 2: mudança para break no "case 0" para voltar a interface inicial do sistema e não a interface anterior na edição de "Cliente" (principal)

![image](https://github.com/user-attachments/assets/d077a9ec-ad42-4741-b4bd-d82a06c60d76)

Funcionalidade 3: informe de que o formato de data é inválido para "Lote" (principal)

![image](https://github.com/user-attachments/assets/7216ed72-cad7-4478-a2f8-7229e28ba843)

Funcionalidade 4: validação de existência de dados nas tabelas derivadas antes de criar agendamentos (principal)

![image](https://github.com/user-attachments/assets/0b1ced8c-a6b5-4d78-9a3b-1e9bfe303e52)

**Comment by HectorSemenssato** [comment]
**UPDATE: "ifs" da funcionalidade 4 separados por exibir dados de consulta e os mesmos dados serem exibidos no decorrer de preenchimento do sistema.

Aguardo de apuração para escolha de mantém separados ou juntos.

**Comment by HectorSemenssato** [comment]
Correções das novas funcionalidades:

Funcionalidade 5: exibição duplicada de consulta para todos os métodos de todas as classes 

![Captura de tela 2024-12-02 212218](https://github.com/user-attachments/assets/b83d9922-1306-433f-b490-7d4a6f238cc2)


Funcionalidade 6: espaçamento de mensagens na classe cliente 

![Captura de tela 2024-12-02 213433](https://github.com/user-attachments/assets/93ed6ace-6baa-4755-8c9b-0d37d5c898e4)


Funcionalidade 7: conflito de mensagens de exibição para exclusão de ID inexistente na base de dados

![Captura de tela 2024-12-02 213922](https://github.com/user-attachments/assets/0b96244b-c125-44fd-bb86-601147c21c8f)

**Comment by camilla-sr** [comment]
Corrigido
