### ISSUE TITLE
Adição de novas funcionalidades #2 

### ISSUE THREAD

**Issue by HectorSemenssato** [camilla-sr/auto-agenda#11]
Funcionalidade 1: adicionado looping de validação de quantidade de números para número de WhatsApp e validação de quantidade de dígitos para ano do carro

![image](https://github.com/user-attachments/assets/fddfab04-08af-4c55-b34f-423b76f7b050)

UPD: o método "concluir agendamento" permite finalizar agendamentos já finalizados

![image](https://github.com/user-attachments/assets/62465b0a-4dbf-465e-b9ff-6d44a0ba4f2d)

**Comment by camilla-sr** [comment]
Updates funcionando
