### ISSUE TITLE
Teste do sistema para operação de edição

### ISSUE THREAD

**Issue by HectorSemenssato** [camilla-sr/auto-agenda#3]
**Peças**

1. Problema ao fazer edição de quantidade (erro de sintaxe) e na opção "Os dois"
2. Numa segunda edição nessa mesma opção, sistema não pergunta o ID a ser editado

**Óleo**

1. Quantidade de garrafas: Erro ao executar query: Data truncation: Incorrect date value: 'null' for column 'data_compra' at row 1
2. Data de compra: Erro ao executar query: Data truncation: Incorrect date value: 'null' for column 'data_vencimento' at row 1
3.  Depois de fazer edições, sistema encerra ao tentar efetuar edição novamente na quantidade de garrafas

**Cliente**

1. Editar todos: concatenação do ano carro incompleta: 
UPDATE cliente set nome_cliente = 'Francisco', whatsapp_cliente = '1145321017', modelo_carro = 'Ford Fusion', ano_carro = '2025 WHERE id_cliente = 1

**Tipo Serviço**

1. Tipo serviço apresenta "Erro ao editar cliente" ao tentar editar.

**Comment by camilla-sr** [comment]
**Peças**
Resolvido laço de repetição e variável reutilizada que verifica ID enviado

**Óleo**
1, 2. Implementado método na Helper para trocar a ordem da data ao inserir no banco e ao trazer em tela
3. Resolvido. Bug com variável de validação de números

**Cliente**
Resolvido. Faltava fechar as aspas simples na variável do ano

**Tipo Serviço**
Resolvido. Mensagem esquecida
