### ISSUE TITLE
Método de edição dinâmica da classe "Agendamento"

### ISSUE THREAD

**Issue by HectorSemenssato** [camilla-sr/auto-agenda#7]
[UPDATE 1]
Falha 1: previsão de entrega sem looping para formato de data inválido

![image](https://github.com/user-attachments/assets/4a4af91b-fb98-4f79-961c-230c98a9613d)

![image](https://github.com/user-attachments/assets/2d121b17-27d4-4549-acbf-fe9b3e2ea5be)

Falha 2: edição de todos os campos sem validações de ID 

![image](https://github.com/user-attachments/assets/22b37880-413d-49c1-ad22-23c7a7f19baa)

![image](https://github.com/user-attachments/assets/adbb6bb4-d2b4-4f16-aaf8-68434660baf4)

Falha 3: exclusão de agendamento com muitas mensagens e dando erro no sistema

![image](https://github.com/user-attachments/assets/1b83778c-90d0-49b1-8b2c-505f96d6d395)

**Comment by camilla-sr** [comment]
Falha 3:
Esse erro não está acontecendo, verifique se há dados no seu banco e se o código foi atualizado para a última versão
![image](https://github.com/user-attachments/assets/d55694db-d2fd-4c29-9531-ce8cfc7a9b5b)

**Comment by HectorSemenssato** [comment]
O problema acontece com ID que não existe na base de dados

**Comment by camilla-sr** [comment]
Falha 1 retificada

**Comment by HectorSemenssato** [comment]
Falha 4: edição com dados validados entrando na field list

![image](https://github.com/user-attachments/assets/f4ca7321-b66c-49e9-91d7-2678af7b032e)


Falha 5: inputMismatchException chamada para criação de agendamento não validando se é um caractere ou número

![image](https://github.com/user-attachments/assets/4448f206-f9d2-454f-8790-41694c540748)
(no ID do cliente, aquilo é um "L" minúsculo)


"Um pequeno detalhe": listarAgendamentos exibindo dado duplicado

![image](https://github.com/user-attachments/assets/a8258a4e-ea27-4adf-8444-c63c57bb2daa)

**Comment by camilla-sr** [comment]
Todas as falhas retificadas

**Comment by HectorSemenssato** [comment]
Falha 6: falha na chamada do método certo de cadastro de agendamento

![image](https://github.com/user-attachments/assets/4b4ce19f-e376-44df-81d1-fab5084a249a)

**Comment by camilla-sr** [comment]
Retificado, requer novo teste

**Comment by HectorSemenssato** [comment]
Correções finalizadas.
