### ISSUE TITLE
Problema(s) da Interface

### ISSUE THREAD

**Issue by HectorSemenssato** [camilla-sr/auto-agenda#8]
Falha 1: sistema encerra ao colocar número que não está dentre as opções válidas (Interfaces: Inicio e Cadastro)

![image](https://github.com/user-attachments/assets/afcae0b6-110e-47a8-a273-a5c5fd770294)

![image](https://github.com/user-attachments/assets/35593e58-9c29-4e67-b37a-9292f464c337)

**Comment by camilla-sr** [comment]
Resolvido. Faltava o default no switch dos dois
