### ISSUE TITLE
Problema(s) de tabelas derivadas

### ISSUE THREAD

**Issue by HectorSemenssato** [camilla-sr/auto-agenda#9]
Falha 1: não é possível excluir IDs que estão sendo utilizadas por outras tabelas (interface: cliente, serviço e funcionário)

![image](https://github.com/user-attachments/assets/4ec87a95-2905-401b-b171-add0c8805555)

![image](https://github.com/user-attachments/assets/c473f990-9c2e-4840-b681-95cd53d87e4d)

![image](https://github.com/user-attachments/assets/aeb83fc5-dbb4-4a13-a177-2decec90c50a)

**Comment by camilla-sr** [comment]
Retificado
